### ISSUE TITLE
Print SWF(file) not working.

### ISSUE THREAD

**Issue by jdcrunchman** [timknip/pyswf#16]
from swf.movie import SWF    <--- works fine
file = open('CT12KORJ001.swf', 'rb' )    <---- works fine
print SWF(file)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.8-intel/egg/swf/movie.py", line 87, in **init**
  File "build/bdist.macosx-10.8-intel/egg/swf/movie.py", line 143, in parse
  File "build/bdist.macosx-10.8-intel/egg/swf/tag.py", line 112, in parse_tags

Why am I getting this?    Where have I made my mistake,   Did I leave anything out?   Did the install go badly?    It didn't indicate so.

Please also reply to my email - jdcrunchman@gmail.com

John

**Comment by ch3c05** [comment]
Same issue here, basically I can't get passed of simply printing the SWF structure at "print SWF(File)".
Issues start with: 

pyswf/swf/movie.py", line 100, in __init__
    self.parse(self._data)

Any ideas?

**Comment by jdcrunchman** [comment]
This issue was started more then 3 years ago,   I have since gone on to
work on other projects.

John
