### ISSUE TITLE
Support python 3

### ISSUE THREAD

**Issue by 5j9** [timknip/pyswf#34]
Please add support for python 3.x.
```python
>>> from swf.movie import SWF
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    from swf.movie import SWF
  File "C:\Users\username\AppData\Local\Programs\Python\Python35-32\lib\site-packages\swf\movie.py", line 4, in <module>
    from tag import SWFTimelineContainer
ImportError: No module named 'tag'
```

**Comment by fgmacedo** [comment]
Hi! Are there any plans to do a pypi release? The published version still without py3 support.

Thanks!

**Comment by BloomAutist47** [comment]
bumping this. will there be any chance pypi support on newer python?
