### ISSUE TITLE
ModuleNotFoundError: No module named 'tag'

### ISSUE THREAD

**Issue by doctorcolossus** [timknip/pyswf#48]
I just installed pyswf 1.5.4 for the first time from pip and was not able to import it due to this error:
```
>>> from swf.movie import SWF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/swf/movie.py", line 4, in <module>
    from tag import SWFTimelineContainer
ModuleNotFoundError: No module named 'tag'
```

**Comment by eric-wieser** [comment]
Looks like the PyPI release of this module doesn't support Python 3
